### ISSUE TITLE
Errors in saving modified .ply in CloudCompare

### ISSUE THREAD

**Issue by kerianVaraine** [francescofugazzi/3dgsconverter#10]
Firstly, thank you for what will be an extremely useful tool to clean and modify 3dgs ply files using cloud compare.

My Issue:
After converting using the command line I imported into CC (2.13.0) and edited point cloud as expected.
On saving the modified point cloud as .ply (ASCII) in CC, many errors occur in process such as:
```
[PLY] 'Failed writing nz of vertex 713880 (ascii output: float)'
[PLY] 'Failed writing ny of vertex 713900 (ascii output: float)'
[PLY] 'Failed writing nx of vertex 714169 (ascii output: float)'
[PLY] 'Failed writing z of vertex 714237 (ascii output: float)'
[PLY] 'Failed writing y of vertex 714357 (ascii output: float)'
[PLY] 'Failed writing x of vertex 714358 (ascii output: float)'
[PLY] 'Failed writing scalar_scal_rot_3 of vertex 714439 (ascii output: float)'
[PLY] 'Failed writing scalar_scal_rot_2 of vertex 714500 (ascii output: float)'
[PLY] 'Failed writing scalar_scal_rot_1 of vertex 714649 (ascii output: float)'
[PLY] 'Failed writing scalar_scal_rot_0 of vertex 714678 (ascii output: float)'
``` 
...and so on, for many other parameters of vertex.

I tried exporting as BIN to the same end.

I jammed a fork into the enter key to see what happened if I accepted all the errors, CC kindly finished its process and logged 
```
File '***.ply' saved successfully
```
On trying to convert output .ply, 3dgsconverter threw errors saying (obviously) ```PlyElementParseError("early end-of-line", ...```

Am I missing something on the CC side to save the parameters?

**Comment by francescofugazzi** [comment]
any chance to share the ply that what saved succesfully and not working with the converter?

**Comment by kerianVaraine** [comment]
[Link to files:](https://drive.google.com/file/d/1723ILuxnIwWdQP5nyTf2lk4OE59sLMdU/view?usp=drive_link)

Process:
Used Jawset PostShot for Pose est, Training, export etc ( `altar_out-80k_2sDensi.ply` )

`$ 3dgsconverter -i altar_out-80k_2sDensi.ply -o altar_cc.ply -f cc --rgb`

Cloudcompare, simple edit to remove some points, 
save as PLY ( `altar_cc-CloudComp.ply`), ASCII, with following Error Log:

<details>
  <summary>Cloud Compare Error Logs</summary>

```
  [12:16:56] [PLY] 'Failed writing scalar_scal_opacity of vertex 47018 (ascii output: float)'
[12:16:59] [PLY] 'Failed writing scalar_scal_f_rest_44 of vertex 78435 (ascii output: float)'
[12:16:59] [PLY] 'Failed writing scalar_scal_f_rest_43 of vertex 78436 (ascii output: float)'
[12:17:00] [PLY] 'Failed writing scalar_scal_f_rest_42 of vertex 78437 (ascii output: float)'
[12:17:01] [PLY] 'Failed writing blue of vertex 78438 (ascii output: uchar)'
[12:17:01] [PLY] 'Failed writing blue of vertex 78438 (ascii output: uchar)'
[12:17:02] [PLY] 'Failed writing blue of vertex 78438 (ascii output: uchar)'
[12:17:02] [PLY] 'Failed writing red of vertex 78439 (ascii output: uchar)'
[12:17:03] [PLY] 'Failed writing red of vertex 78439 (ascii output: uchar)'
[12:17:03] [PLY] 'Failed writing scalar_scal_f_rest_36 of vertex 88172 (ascii output: float)'
[12:17:05] [PLY] 'Failed writing scalar_scal_f_rest_35 of vertex 205796 (ascii output: float)'
[12:17:06] [PLY] 'Failed writing scalar_scal_f_rest_34 of vertex 207147 (ascii output: float)'
[12:17:06] [PLY] 'Failed writing scalar_scal_f_rest_33 of vertex 213411 (ascii output: float)'
[12:17:07] [PLY] 'Failed writing scalar_scal_f_rest_32 of vertex 215196 (ascii output: float)'
[12:17:07] [PLY] 'Failed writing scalar_scal_f_rest_31 of vertex 217373 (ascii output: float)'
[12:17:08] [PLY] 'Failed writing scalar_scal_f_rest_30 of vertex 271415 (ascii output: float)'
[12:17:08] [PLY] 'Failed writing scalar_scal_f_rest_29 of vertex 271419 (ascii output: float)'
[12:17:08] [PLY] 'Failed writing scalar_scal_f_rest_28 of vertex 271423 (ascii output: float)'
[12:17:08] [PLY] 'Failed writing scalar_scal_f_rest_27 of vertex 271427 (ascii output: float)'
[12:17:08] [PLY] 'Failed writing scalar_scal_f_rest_26 of vertex 271431 (ascii output: float)'
[12:17:09] [PLY] 'Failed writing scalar_scal_f_rest_25 of vertex 312612 (ascii output: float)'
[12:17:09] [PLY] 'Failed writing scalar_scal_f_rest_24 of vertex 326225 (ascii output: float)'
[12:17:10] [PLY] 'Failed writing scalar_scal_f_rest_23 of vertex 330284 (ascii output: float)'
[12:17:10] [PLY] 'Failed writing scalar_scal_f_rest_22 of vertex 338664 (ascii output: float)'
[12:17:10] [PLY] 'Failed writing scalar_scal_f_rest_21 of vertex 354078 (ascii output: float)'
[12:17:10] [PLY] 'Failed writing scalar_scal_f_rest_20 of vertex 356950 (ascii output: float)'
[12:17:10] [PLY] 'Failed writing scalar_scal_f_rest_19 of vertex 360884 (ascii output: float)'
[12:17:11] [PLY] 'Failed writing scalar_scal_f_rest_18 of vertex 366556 (ascii output: float)'
[12:17:11] [PLY] 'Failed writing scalar_scal_f_rest_17 of vertex 374295 (ascii output: float)'
[12:17:11] [PLY] 'Failed writing scalar_scal_f_rest_16 of vertex 384708 (ascii output: float)'
[12:17:11] [PLY] 'Failed writing scalar_scal_f_rest_15 of vertex 398176 (ascii output: float)'
[12:17:12] [PLY] 'Failed writing scalar_scal_f_rest_14 of vertex 401610 (ascii output: float)'
[12:17:12] [PLY] 'Failed writing scalar_scal_f_rest_13 of vertex 408721 (ascii output: float)'
[12:17:12] [PLY] 'Failed writing scalar_scal_f_rest_12 of vertex 414101 (ascii output: float)'
[12:17:12] [PLY] 'Failed writing scalar_scal_f_rest_11 of vertex 439336 (ascii output: float)'
[12:17:13] [PLY] 'Failed writing scalar_scal_f_rest_10 of vertex 463469 (ascii output: float)'
[12:17:13] [PLY] 'Failed writing scalar_scal_f_rest_9 of vertex 463691 (ascii output: float)'
[12:17:13] [PLY] 'Failed writing scalar_scal_f_rest_8 of vertex 469269 (ascii output: float)'
[12:17:13] [PLY] 'Failed writing scalar_scal_f_rest_7 of vertex 470213 (ascii output: float)'
[12:17:13] [PLY] 'Failed writing scalar_scal_f_rest_6 of vertex 473206 (ascii output: float)'
[12:17:14] [PLY] 'Failed writing scalar_scal_f_rest_5 of vertex 476488 (ascii output: float)'
[12:17:14] [PLY] 'Failed writing scalar_scal_f_rest_4 of vertex 478161 (ascii output: float)'
[12:17:14] [PLY] 'Failed writing scalar_scal_f_rest_3 of vertex 508178 (ascii output: float)'
[12:17:14] [PLY] 'Failed writing scalar_scal_f_rest_2 of vertex 513289 (ascii output: float)'
[12:17:15] [PLY] 'Failed writing scalar_scal_f_rest_1 of vertex 522049 (ascii output: float)'
[12:17:15] [PLY] 'Failed writing scalar_scal_f_rest_0 of vertex 523730 (ascii output: float)'
[12:17:15] [PLY] 'Failed writing scalar_scal_f_dc_2 of vertex 526236 (ascii output: float)'
[12:17:15] [PLY] 'Failed writing scalar_scal_f_dc_1 of vertex 533254 (ascii output: float)'
[12:17:15] [PLY] 'Failed writing scalar_scal_f_dc_0 of vertex 533722 (ascii output: float)'
[12:17:16] [PLY] 'Failed writing nz of vertex 553101 (ascii output: float)'
[12:17:16] [PLY] 'Failed writing ny of vertex 556423 (ascii output: float)'
[12:17:16] [PLY] 'Failed writing nx of vertex 556577 (ascii output: float)'
[12:17:16] [PLY] 'Failed writing blue of vertex 556579 (ascii output: uchar)'
[12:17:16] [PLY] 'Failed writing blue of vertex 556579 (ascii output: uchar)'
[12:17:16] [PLY] 'Failed writing blue of vertex 556579 (ascii output: uchar)'
[12:17:16] [PLY] 'Failed writing blue of vertex 556579 (ascii output: uchar)'
[12:17:16] [PLY] 'Failed writing blue of vertex 556579 (ascii output: uchar)'
[12:17:16] [PLY] 'Failed writing blue of vertex 556579 (ascii output: uchar)'
[12:17:17] [PLY] 'Failed writing red of vertex 556580 (ascii output: uchar)'
[12:17:17] [PLY] 'Failed writing red of vertex 556581 (ascii output: uchar)'
[12:17:17] [PLY] 'Failed writing red of vertex 556581 (ascii output: uchar)'
[12:17:17] [PLY] 'Failed writing blue of vertex 556581 (ascii output: uchar)'
[12:17:18] [PLY] 'Failed writing green of vertex 556582 (ascii output: uchar)'
[12:17:18] [PLY] 'Failed writing red of vertex 556583 (ascii output: uchar)'
[12:17:18] [PLY] 'Failed writing scalar_scal_scale_0 of vertex 560071 (ascii output: float)'
[12:17:19] [PLY] 'Failed writing scalar_scal_opacity of vertex 584670 (ascii output: float)'
[12:17:19] [PLY] 'Failed writing scalar_scal_f_rest_44 of vertex 589056 (ascii output: float)'
[12:17:19] [PLY] 'Failed writing scalar_scal_f_rest_43 of vertex 589360 (ascii output: float)'
[12:17:19] [PLY] 'Failed writing scalar_scal_f_rest_42 of vertex 593176 (ascii output: float)'
[12:17:19] [PLY] 'Failed writing blue of vertex 593177 (ascii output: uchar)'
[12:17:19] [PLY] 'Failed writing blue of vertex 593177 (ascii output: uchar)'
[12:17:20] [PLY] 'Failed writing blue of vertex 593177 (ascii output: uchar)'
[12:17:20] [PLY] 'Failed writing red of vertex 593179 (ascii output: uchar)'
[12:17:20] [PLY] 'Failed writing red of vertex 593179 (ascii output: uchar)'
[12:17:20] [PLY] 'Failed writing scalar_scal_f_rest_36 of vertex 611460 (ascii output: float)'
[12:17:20] [PLY] 'Failed writing scalar_scal_f_rest_35 of vertex 611612 (ascii output: float)'
[12:17:20] [PLY] 'Failed writing scalar_scal_f_rest_34 of vertex 611613 (ascii output: float)'
[12:17:20] [PLY] 'Failed writing scalar_scal_f_rest_33 of vertex 611621 (ascii output: float)'
[12:17:21] [PLY] 'Failed writing scalar_scal_f_rest_32 of vertex 611647 (ascii output: float)'
[12:17:21] [PLY] 'Failed writing scalar_scal_f_rest_31 of vertex 613504 (ascii output: float)'
[12:17:21] [PLY] 'Failed writing scalar_scal_f_rest_30 of vertex 613508 (ascii output: float)'
[12:17:21] [PLY] 'Failed writing scalar_scal_f_rest_29 of vertex 615929 (ascii output: float)'
[12:17:21] [PLY] 'Failed writing scalar_scal_f_rest_28 of vertex 616637 (ascii output: float)'
[12:17:21] [PLY] 'Failed writing scalar_scal_f_rest_27 of vertex 616912 (ascii output: float)'
[12:17:21] [PLY] 'Failed writing scalar_scal_f_rest_26 of vertex 617359 (ascii output: float)'
[12:17:21] [PLY] 'Failed writing scalar_scal_f_rest_25 of vertex 618645 (ascii output: float)'
[12:17:22] [PLY] 'Failed writing scalar_scal_f_rest_24 of vertex 621176 (ascii output: float)'
[12:17:22] [PLY] 'Failed writing scalar_scal_f_rest_23 of vertex 621288 (ascii output: float)'
[12:17:22] [PLY] 'Failed writing scalar_scal_f_rest_22 of vertex 622050 (ascii output: float)'
[12:17:22] [PLY] 'Failed writing scalar_scal_f_rest_21 of vertex 622060 (ascii output: float)'
[12:17:22] [PLY] 'Failed writing scalar_scal_f_rest_20 of vertex 624900 (ascii output: float)'
[12:17:22] [PLY] 'Failed writing scalar_scal_f_rest_19 of vertex 630989 (ascii output: float)'
[12:17:22] [PLY] 'Failed writing scalar_scal_f_rest_18 of vertex 634762 (ascii output: float)'
[12:17:23] [PLY] 'Failed writing scalar_scal_f_rest_17 of vertex 636822 (ascii output: float)'
[12:17:23] [PLY] 'Failed writing scalar_scal_f_rest_16 of vertex 638729 (ascii output: float)'
[12:17:23] [PLY] 'Failed writing scalar_scal_f_rest_15 of vertex 652121 (ascii output: float)'
[12:17:23] [PLY] 'Failed writing scalar_scal_f_rest_14 of vertex 661240 (ascii output: float)'
[12:17:23] [PLY] 'Failed writing scalar_scal_f_rest_13 of vertex 663418 (ascii output: float)'
[12:17:23] [PLY] 'Failed writing scalar_scal_f_rest_12 of vertex 663419 (ascii output: float)'
[12:17:24] [PLY] 'Failed writing scalar_scal_f_rest_11 of vertex 666335 (ascii output: float)'
[12:17:24] [PLY] 'Failed writing scalar_scal_f_rest_10 of vertex 674886 (ascii output: float)'
[12:17:24] [PLY] 'Failed writing scalar_scal_f_rest_9 of vertex 690041 (ascii output: float)'
[12:17:24] [PLY] 'Failed writing scalar_scal_f_rest_8 of vertex 691945 (ascii output: float)'
[12:17:24] [PLY] 'Failed writing scalar_scal_f_rest_7 of vertex 691946 (ascii output: float)'
[12:17:24] [PLY] 'Failed writing scalar_scal_f_rest_6 of vertex 693333 (ascii output: float)'
[12:17:25] [PLY] 'Failed writing scalar_scal_f_rest_5 of vertex 705762 (ascii output: float)'
[12:17:25] [PLY] 'Failed writing scalar_scal_f_rest_4 of vertex 705764 (ascii output: float)'
[12:17:25] [PLY] 'Failed writing scalar_scal_f_rest_3 of vertex 705963 (ascii output: float)'
[12:17:25] [PLY] 'Failed writing scalar_scal_f_rest_2 of vertex 705965 (ascii output: float)'
[12:17:25] [PLY] 'Failed writing scalar_scal_f_rest_1 of vertex 707074 (ascii output: float)'
[12:17:25] [PLY] 'Failed writing scalar_scal_f_rest_0 of vertex 707075 (ascii output: float)'
[12:17:25] [PLY] 'Failed writing scalar_scal_f_dc_2 of vertex 707081 (ascii output: float)'
[12:17:25] [PLY] 'Failed writing scalar_scal_f_dc_1 of vertex 707121 (ascii output: float)'
[12:17:25] [PLY] 'Failed writing scalar_scal_f_dc_0 of vertex 707130 (ascii output: float)'
[12:17:25] [PLY] 'Failed writing nz of vertex 707955 (ascii output: float)'
[12:17:26] [PLY] 'Failed writing ny of vertex 708652 (ascii output: float)'
[12:17:26] [PLY] 'Failed writing nx of vertex 711934 (ascii output: float)'
[12:17:26] [PLY] 'Failed writing blue of vertex 711937 (ascii output: uchar)'
[12:17:26] [PLY] 'Failed writing blue of vertex 711937 (ascii output: uchar)'
[12:17:26] [PLY] 'Failed writing blue of vertex 711937 (ascii output: uchar)'
[12:17:26] [PLY] 'Failed writing blue of vertex 711937 (ascii output: uchar)'
[12:17:26] [PLY] 'Failed writing blue of vertex 711937 (ascii output: uchar)'
[12:17:26] [PLY] 'Failed writing red of vertex 711938 (ascii output: uchar)'
[12:17:26] [PLY] 'Failed writing red of vertex 711938 (ascii output: uchar)'
[12:17:26] [PLY] 'Failed writing red of vertex 711938 (ascii output: uchar)'
[12:17:26] [PLY] 'Failed writing green of vertex 711939 (ascii output: uchar)'
[12:17:27] [PLY] 'Failed writing red of vertex 711940 (ascii output: uchar)'
[12:17:27] [PLY] 'Failed writing scalar_scal_scale_2 of vertex 718334 (ascii output: float)'
[12:17:27] [PLY] 'Failed writing scalar_scal_scale_1 of vertex 718838 (ascii output: float)'
[12:17:27] [PLY] 'Failed writing scalar_scal_scale_0 of vertex 726166 (ascii output: float)'
[12:17:28] [PLY] 'Failed writing scalar_scal_opacity of vertex 763406 (ascii output: float)'
[12:17:28] [PLY] 'Failed writing scalar_scal_f_rest_44 of vertex 763409 (ascii output: float)'
[12:17:29] [PLY] 'Failed writing scalar_scal_f_rest_43 of vertex 763411 (ascii output: float)'
[12:17:29] [PLY] 'Failed writing scalar_scal_f_rest_42 of vertex 763412 (ascii output: float)'
[12:17:29] [PLY] 'Failed writing blue of vertex 763413 (ascii output: uchar)'
[12:17:29] [PLY] 'Failed writing blue of vertex 763413 (ascii output: uchar)'
[12:17:29] [PLY] 'Failed writing blue of vertex 763413 (ascii output: uchar)'
[12:17:29] [PLY] 'Failed writing scalar_scal_f_rest_38 of vertex 763413 (ascii output: float)'
[12:17:30] [PLY] 'Failed writing red of vertex 763415 (ascii output: uchar)'
[12:17:30] [PLY] 'Failed writing scalar_scal_f_rest_36 of vertex 763417 (ascii output: float)'
[12:17:30] [PLY] 'Failed writing scalar_scal_f_rest_35 of vertex 763421 (ascii output: float)'
[12:17:30] [PLY] 'Failed writing scalar_scal_f_rest_34 of vertex 763422 (ascii output: float)'
[12:17:30] [PLY] 'Failed writing scalar_scal_f_rest_33 of vertex 763429 (ascii output: float)'
[12:17:30] [PLY] 'Failed writing scalar_scal_f_rest_32 of vertex 763492 (ascii output: float)'
[12:17:30] [PLY] 'Failed writing scalar_scal_f_rest_31 of vertex 763495 (ascii output: float)'
[12:17:30] [PLY] 'Failed writing scalar_scal_f_rest_30 of vertex 763496 (ascii output: float)'
[12:17:30] [PLY] 'Failed writing scalar_scal_f_rest_29 of vertex 763497 (ascii output: float)'
[12:17:30] [PLY] 'Failed writing scalar_scal_f_rest_28 of vertex 770400 (ascii output: float)'
[12:17:31] [PLY] 'Failed writing scalar_scal_f_rest_27 of vertex 772193 (ascii output: float)'
[12:17:31] [PLY] 'Failed writing scalar_scal_f_rest_26 of vertex 773196 (ascii output: float)'
[12:17:31] [PLY] 'Failed writing scalar_scal_f_rest_25 of vertex 773197 (ascii output: float)'
[12:17:31] [PLY] 'Failed writing scalar_scal_f_rest_24 of vertex 775448 (ascii output: float)'
[12:17:31] [PLY] 'Failed writing scalar_scal_f_rest_23 of vertex 775449 (ascii output: float)'
[12:17:31] [PLY] 'Failed writing scalar_scal_f_rest_22 of vertex 775450 (ascii output: float)'
[12:17:31] [PLY] 'Failed writing scalar_scal_f_rest_21 of vertex 775451 (ascii output: float)'
[12:17:31] [PLY] 'Failed writing scalar_scal_f_rest_20 of vertex 775733 (ascii output: float)'
[12:17:31] [PLY] 'Failed writing scalar_scal_f_rest_19 of vertex 778904 (ascii output: float)'
[12:17:31] [PLY] 'Failed writing scalar_scal_f_rest_18 of vertex 779095 (ascii output: float)'
[12:17:32] [PLY] 'Failed writing scalar_scal_f_rest_17 of vertex 780642 (ascii output: float)'
[12:17:32] [PLY] 'Failed writing scalar_scal_f_rest_16 of vertex 792689 (ascii output: float)'
[12:17:32] [PLY] 'Failed writing scalar_scal_f_rest_15 of vertex 796330 (ascii output: float)'
[12:17:32] [PLY] 'Failed writing scalar_scal_f_rest_14 of vertex 799550 (ascii output: float)'
[12:17:32] [PLY] 'Failed writing scalar_scal_f_rest_13 of vertex 801476 (ascii output: float)'
[12:17:32] [PLY] 'Failed writing scalar_scal_f_rest_12 of vertex 804088 (ascii output: float)'
[12:17:33] [PLY] 'Failed writing scalar_scal_f_rest_11 of vertex 808890 (ascii output: float)'
[12:17:33] [PLY] 'Failed writing scalar_scal_f_rest_10 of vertex 810970 (ascii output: float)'
[12:17:33] [PLY] 'Failed writing scalar_scal_f_rest_9 of vertex 819157 (ascii output: float)'
[12:17:33] [PLY] 'Failed writing scalar_scal_f_rest_8 of vertex 827655 (ascii output: float)'
[12:17:33] [PLY] 'Failed writing scalar_scal_f_rest_7 of vertex 835773 (ascii output: float)'
[12:17:34] [PLY] 'Failed writing scalar_scal_f_rest_6 of vertex 849387 (ascii output: float)'
[12:17:34] [PLY] 'Failed writing scalar_scal_f_rest_5 of vertex 852005 (ascii output: float)'
[12:17:35] [PLY] 'Failed writing scalar_scal_f_rest_4 of vertex 894078 (ascii output: float)'
[12:17:35] [PLY] 'Failed writing scalar_scal_f_rest_3 of vertex 905195 (ascii output: float)'
[12:17:36] [PLY] 'Failed writing scalar_scal_f_rest_2 of vertex 921526 (ascii output: float)'
[12:17:36] [PLY] 'Failed writing scalar_scal_f_rest_1 of vertex 921842 (ascii output: float)'
[12:17:36] [PLY] 'Failed writing scalar_scal_f_rest_0 of vertex 923792 (ascii output: float)'
[12:17:36] [PLY] 'Failed writing scalar_scal_f_dc_2 of vertex 923797 (ascii output: float)'
[12:17:36] [PLY] 'Failed writing scalar_scal_f_dc_1 of vertex 924648 (ascii output: float)'
[12:17:37] [PLY] 'Failed writing scalar_scal_f_dc_0 of vertex 926634 (ascii output: float)'
[12:17:37] [PLY] 'Failed writing nz of vertex 934855 (ascii output: float)'

[12:17:37] [I/O] File '/Users/admin/Documents/2024/splats/altar_cc - CloudComp.ply' saved successfully
```

</details>

`$ 3dgsconverter -i altar_cc-CloudComp.ply -o altar_3dgs.ply -f 3dgs`

<details>
 <summary>3dgsconverter Error Logs</summary>

```
3D Gaussian Splatting Converter: 0.2
Detected source format: cc
Traceback (most recent call last):
  File "/Users/admin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/plyfile.py", line 615, in _read_txt
    self._data[prop.name][k] = prop._from_fields(fields)
  File "/Users/admin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/plyfile.py", line 801, in _from_fields
    return _np.dtype(self.dtype()).type(next(fields))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/.pyenv/versions/3.9.11/bin/3dgsconverter", line 33, in <module>
    sys.exit(load_entry_point('gsconverter==0.2', 'console_scripts', '3dgsconverter')())
  File "/Users/admin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/gsconverter/main.py", line 93, in main
    data = PlyData.read(args.input)
  File "/Users/admin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/plyfile.py", line 173, in read
    elt._read(data_stream, data.text, data.byte_order, mmap,
  File "/Users/admin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/plyfile.py", line 514, in _read
    self._read_txt(stream)
  File "/Users/admin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/plyfile.py", line 617, in _read_txt
    raise PlyElementParseError("early end-of-line",
plyfile.PlyElementParseError: element 'vertex': row 943674: property 'scalar_scal_f_rest_3': early end-of-line
```

</details>

**Comment by francescofugazzi** [comment]
thanks for providing me the archive. I opened your ply file and I noticed it was processed only with baisc colors and no spherical harmonics. In my converter i took into consideration only files with SH3 and full properties.
So now we know why it wasn't working as expected.
I can't promise anything but I will look into that :)

**Comment by kerianVaraine** [comment]
Brilliant, thank you for the lead. So much to learn.
This is merely a 'me' issue relating to workflow.
